# Generated by Django 5.2.3 on 2025-06-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_evidence',
            field=models.FileField(blank=True, null=True, upload_to='response_evidence/'),
        ),
        migrations.CreateModel(
            name='DepartmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('expected_resolution_date', models.DateField(blank=True, null=True)),
                ('response_evidence', models.FileField(blank=True, null=True, upload_to='response_evidence/')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.complaint')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
