# Generated by Django 5.2.3 on 2025-06-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_department_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
