# Generated by Django 5.2.3 on 2025-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whatsapplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
