# Generated by Django 5.2.3 on 2025-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complaint_priority_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=70)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_score',
            field=models.IntegerField(default=50),
        ),
    ]
