# Generated by Django 5.2.3 on 2025-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_departmentscore_customuser_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='department_response',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolution_deadline',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='response_evidence',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
