# Generated by Django 5.2.3 on 2025-07-21 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
