# Generated by Django 5.2.3 on 2025-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_department_superior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='department',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_time',
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
