# Generated by Django 5.2.3 on 2025-07-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_complaint_custom_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
    ]
