# Generated by Django 5.2.3 on 2025-07-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_complaint_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.complaint')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.complaint')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='complainthistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='complainthistory',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='departmentresponse',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='departmentresponse',
            name='responder',
        ),
        migrations.DeleteModel(
            name='DepartmentScore',
        ),
        migrations.DeleteModel(
            name='ComplaintHistory',
        ),
        migrations.DeleteModel(
            name='DepartmentResponse',
        ),
    ]
