# Generated by Django 5.2.3 on 2025-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_complaintassignment_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='support_file',
            field=models.FileField(blank=True, null=True, upload_to='supportfiles/'),
        ),
    ]
