# Generated by Django 5.2.3 on 2025-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_response_support_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_academic',
            field=models.BooleanField(default=False),
        ),
    ]
