# Generated by Django 5.2.3 on 2025-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_department_is_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='incident_timestamp',
            field=models.DateTimeField(),
        ),
    ]
