# Generated by Django 5.2.3 on 2025-07-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_complaint_incident_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
