# Generated by Django 5.2.3 on 2025-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
