# Generated by Django 5.2.3 on 2025-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_complaint_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='asd', max_length=13),
            preserve_default=False,
        ),
    ]
